---
name: Pull Request CI
on:  # yamllint disable-line rule:truthy
  workflow_dispatch: {}
  pull_request:
    paths:
      - '**.go'

jobs:
  build:
    name: Build
    uses: 0xpolygon/polygon-edge/.github/workflows/build.yml@develop

  test:
    name: Test
    uses: 0xpolygon/polygon-edge/.github/workflows/test.yml@develop
    needs: build

  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          args: --org=${{ secrets.SNYK_ORG }} --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  snyk-code:
    name: Snyk Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk SAST to check for code vulnerabilities
        uses: snyk/actions/golang@master
        with:
          command: code test
          args: --org=${{ secrets.SNYK_ORG }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
