---
name: E2E Legacy Tests
on: # yamllint disable-line rule:truthy
  workflow_call:
    outputs:
      workflow_output:
        description: "E2E Legacy Tests output"
        value: ${{ jobs.e2e_legacy.outputs.e2e_legacy_output_failure }}

jobs:
  e2e_legacy:
    name: Run E2E Legacy Tests
    runs-on: ubuntu-latest
    env:
      E2E_TESTS: true
      E2E_LOGS: true
      CI_VERBOSE: true
    outputs:
      e2e_legacy_output_failure: ${{ steps.run_e2e_legacy_failure.outputs.test_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive
      - name: Install Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.20.x
      - name: Run tests
        run: make test-e2e-legacy
      - name: Run tests failed
        if: failure()
        id: run_e2e_legacy_failure
        run: echo "test_output=false" >> $GITHUB_OUTPUT
      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: e2e-legacy-logs
          path: e2e-logs-*/
          retention-days: 30
