---
name: PolyBFT E2E tests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      workflow_output:
        description: "E2E output"
        value: ${{ jobs.build.outputs.e2e_output_failure }} 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      E2E_TESTS: true
      E2E_LOGS: true
      CI_VERBOSE: true
    outputs:
      e2e_output_failure: ${{ steps.run_e2e_failure.outputs.test_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          check-latest: true
          cache-dependency-path: go.sum

      - name: Run tests
        run: make test-e2e-polybft

      - name: Run tests failed
        if: failure()
        id: run_e2e_failure
        run: echo "test_output=false" >> $GITHUB_OUTPUT

      - name: Archive test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-logs
          path: e2e-logs-*/
          retention-days: 30
