---
name: Notification - Deploy Network
on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      environment:
        description: The environment to run against
        type: string
        required: true
      deploy_network_terraform_output:
        description: "Deploy Network - Terraform output"
        type: string
        required: true
      deploy_network_ansible_output:
        description: "Deploy Network - Ansible output"
        type: string
        required: true
      rpc_url:
        description: "JSON-RPC URL"
        type: string
        required: true
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notification:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: Short SHA
        id: short_sha
        run: echo "value=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_OUTPUT
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.25.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          green_color: '#03C03C'
          red_color: '#E60012'
          succeed_bnt: 'primary'
          failed_bnt: 'danger'
        with:
          payload: |
            {
              "attachments": [
                {
                  "color": "${{ inputs.deploy_network_terraform_output == '' && inputs.deploy_network_ansible_output == '' && env.green_color || env.red_color }}",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Deploy ${{ inputs.environment }}net"
                      }
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Environment: *${{ inputs.environment }}*"
                        }
                      ]
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Commit: *<https://github.com/${{ github.repository }}/tree/${{ github.sha }}|${{ steps.short_sha.outputs.value }}>*"
                        }
                      ]
                    },
                    {
                      "type": "context",
                      "elements": [
                        {
                          "type": "mrkdwn",
                          "text": "Triggered by: *${{ github.triggering_actor }}*"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "Workflow Run"
                          },
                          "style": "${{ inputs.deploy_network_terraform_output == '' && inputs.deploy_network_ansible_output == '' && env.succeed_bnt || env.failed_bnt }}",
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                        },
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "JSON-RPC"
                          },
                          "url": "http://${{ inputs.rpc_url }}"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
